apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/percona-pg-gcp-cluster.git'
    targetRevision: HEAD
    path: percona-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: percona-pg
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
