tenant:
  name: percona-minio
  credsSecret:
    name: minio-creds
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      size: 10Gi
  mountPath: /export
  requestAutoCert: false
