apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://operator.min.io/         # Official Helm repo
    chart: tenant                             # The chart name
    targetRevision: 5.0.11                    # Chart version (update if needed)
    helm:
      values: |
        tenant:
          name: percona-minio
          credsSecret:
            name: minio-creds                 # Must exist in the target namespace
          pools:
            - name: pool-0
              servers: 1
              volumesPerServer: 1
              size: 10Gi
          mountPath: /export
          requestAutoCert: false
  destination:
    server: https://kubernetes.default.svc
    namespace: my-new-namespace               # Same namespace operator watches
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
