apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-secret
  namespace: argocd
spec:
  destination:
    namespace: my-new-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/marwan-ghonem/percona-pg-gcp-cluster.git
    path: bootstrap
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
