apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marwan-ghonem/percona-pg-gcp-cluster.git
    targetRevision: main
    path: minio-tenant          # <== This is your local Helm chart path
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-new-namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
